DROP INDEX IF EXISTS idx_signals_vuln_id;
DROP INDEX IF EXISTS idx_signals_type;
DROP INDEX IF EXISTS idx_signals_observed_at;
CREATE INDEX IF NOT EXISTS idx_signals_identity     ON signals(vuln_id, signal_type, provider);
CREATE INDEX IF NOT EXISTS idx_signals_latest       ON signals(vuln_id, signal_type, observed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_signals_provider     ON signals(provider);
CREATE INDEX IF NOT EXISTS idx_findings_vuln_id     ON findings(vuln_id);
CREATE INDEX IF NOT EXISTS idx_findings_asset_id    ON findings(asset_id);
CREATE INDEX IF NOT EXISTS idx_findings_risk_score  ON findings(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_asset_observations_asset_kind ON asset_observations(asset_id, kind, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_asset_observations_observed_at ON asset_observations(observed_at);
DROP INDEX IF EXISTS idx_fetch_log_feed;
CREATE INDEX IF NOT EXISTS idx_fetch_log_feed       ON fetch_log(feed, attempted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_epss_current_epss    ON epss_current(epss DESC);
CREATE INDEX IF NOT EXISTS idx_epss_current_percentile ON epss_current(percentile DESC);
